export const siteLocales = [
  // {
  //   code: 'BG',
  //   name: 'Bulgarian',
  //   icon: 'i-twemoji:flag-bulgaria',
  //   value: 'bg',
  //   label: 'български',
  // },
  // { code: 'CS', name: 'Czech', icon: 'i-twemoji:flag-czechia', value: 'cs', label: 'čeština' },
  // { code: 'DA', name: 'Danish', icon: 'i-twemoji:flag-denmark', value: 'da', label: 'dansk' },
  // { code: 'DE', name: 'German', icon: 'i-twemoji:flag-germany', value: 'de', label: 'Deutsch' },
  // { code: 'EL', name: 'Greek', icon: 'i-twemoji:flag-greece', value: 'el', label: 'ελληνικά' },
  {
    code: 'EN-GB',
    name: 'English (British)',
    icon: 'i-twemoji:flag-united-kingdom',
    value: 'en',
    label: 'English (British)',
  },
  // {
  //   code: 'EN-US',
  //   name: 'English (American)',
  //   icon: 'i-twemoji:flag-united-states',
  //   value: 'en',
  //   label: 'English (American)',
  // },
  // { code: 'ES', name: 'Spanish', icon: 'i-twemoji:flag-spain', value: 'es', label: 'español' },
  // { code: 'ET', name: 'Estonian', icon: 'i-twemoji:flag-estonia', value: 'ee', label: 'eesti' },
  // { code: 'FI', name: 'Finnish', icon: 'i-twemoji:flag-finland', value: 'fi', label: 'suomi' },
  // { code: 'FR', name: 'French', icon: 'i-twemoji:flag-france', value: 'fr', label: 'français' },
  // { code: 'HU', name: 'Hungarian', icon: 'i-twemoji:flag-hungary', value: 'hu', label: 'magyar' },
  // {
  //   code: 'ID',
  //   name: 'Indonesian',
  //   icon: 'i-twemoji:flag-indonesia',
  //   value: 'id',
  //   label: 'Bahasa Indonesia',
  // },
  // { code: 'IT', name: 'Italian', icon: 'i-twemoji:flag-italy', value: 'it', label: 'italiano' },
  // { code: 'JA', name: 'Japanese', icon: 'i-twemoji:flag-japan', value: 'ja', label: '日本語' },
  // { code: 'KO', name: 'Korean', icon: 'i-twemoji:flag-south-korea', value: 'ko', label: '한국어' },
  // {
  //   code: 'LT',
  //   name: 'Lithuanian',
  //   icon: 'i-twemoji:flag-lithuania',
  //   value: 'lt',
  //   label: 'lietuvių',
  // },
  // { code: 'LV', name: 'Latvian', icon: 'i-twemoji:flag-latvia', value: 'lv', label: 'latviešu' },
  // {
  //   code: 'NB',
  //   name: 'Norwegian (Bokmål)',
  //   icon: 'i-twemoji:flag-norway',
  //   value: 'nb',
  //   label: 'norsk',
  // },
  // {
  //   code: 'NL',
  //   name: 'Dutch',
  //   icon: 'i-twemoji:flag-netherlands',
  //   value: 'nl',
  //   label: 'Nederlands',
  // },
  // { code: 'PL', name: 'Polish', icon: 'i-twemoji:flag-poland', value: 'pl', label: 'polski' },
  // {
  //   code: 'PT-BR',
  //   name: 'Portuguese (Brazilian)',
  //   icon: 'i-twemoji:flag-brazil',
  //   value: 'pt-BR',
  //   label: 'Português (Brasil)',
  // },
  // {
  //   code: 'PT-PT',
  //   name: 'Portuguese',
  //   icon: 'i-twemoji:flag-portugal',
  //   value: 'pt-PT',
  //   label: 'Português (Portugal)',
  // },
  // { code: 'RO', name: 'Romanian', icon: 'i-twemoji:flag-romania', value: 'ro', label: 'română' },
  // { code: 'RU', name: 'Russian', icon: 'i-twemoji:flag-russia', value: 'ru', label: 'русский' },
  // { code: 'SK', name: 'Slovak', icon: 'i-twemoji:flag-slovakia', value: 'sk', label: 'slovenčina' },
  // {
  //   code: 'SL',
  //   name: 'Slovenian',
  //   icon: 'i-twemoji:flag-slovenia',
  //   value: 'sl',
  //   label: 'slovenščina',
  // },
  { code: 'SV', name: 'Swedish', icon: 'i-twemoji:flag-sweden', value: 'sv', label: 'svenska' },
  // { code: 'TR', name: 'Turkish', icon: 'i-twemoji:flag-turkey', value: 'tr', label: 'Türkçe' },
  // {
  //   code: 'UK',
  //   name: 'Ukrainian',
  //   icon: 'i-twemoji:flag-ukraine',
  //   value: 'uk',
  //   label: 'українська',
  // },
  // {
  //   code: 'ZH',
  //   name: 'Chinese (simplified)',
  //   icon: 'i-twemoji:flag-china',
  //   value: 'zh',
  //   label: '简体中文',
  // },
]
